[project]
name = "aseprite-universal-pixel-theme"
version = "0.0.0"
requires-python = ">=3.14"

dependencies = [
    "httpx[http2]==0.28.1",
    "tqdm==4.67.1",
    "lxml==6.0.2",
    "fonttools==4.61.1",
    "pypng==0.20220715.0",
    "markdown==3.10",
]
